version: '3.9'

services:

  api:
    # image: nodejs_api
    build: .
    ports: 
      - 8000:8000
    # volumes:
    #   - .:/usr/src/app
    # links:
    #   - mongo_db
    environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      # - ME_CONGIG_MONGODB_SERVER=dmongodb
      PORT: 8000
      # MONGODB_URI: mongodb://localhost:27017/contacts
      # DB_NAME: contacts
      # NAME: root
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    container_name: db_container
    restart: always
    environment:
      - MONGODB_INITDB_DATABASE=contacts
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db
    
volumes:
  mongodb_data_container:
  